/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface MyListComponent {
        "listData": Array<string>;
        "listName": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyListComponentElement extends Components.MyListComponent, HTMLStencilElement {
    }
    var HTMLMyListComponentElement: {
        prototype: HTMLMyListComponentElement;
        new (): HTMLMyListComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-list-component": HTMLMyListComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface MyListComponent {
        "listData"?: Array<string>;
        "listName"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-list-component": MyListComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-list-component": LocalJSX.MyListComponent & JSXBase.HTMLAttributes<HTMLMyListComponentElement>;
        }
    }
}
