/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
    }
    interface UlqList {
        "listData": Array<string>;
        "listName": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLUlqListElement extends Components.UlqList, HTMLStencilElement {
    }
    var HTMLUlqListElement: {
        prototype: HTMLUlqListElement;
        new (): HTMLUlqListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ulq-list": HTMLUlqListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
    }
    interface UlqList {
        "listData"?: Array<string>;
        "listName"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ulq-list": UlqList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ulq-list": LocalJSX.UlqList & JSXBase.HTMLAttributes<HTMLUlqListElement>;
        }
    }
}
